- o-fish-ios/Helpers/Constants.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/Views/MainNavigationRootView.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/LoadedStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
[-] `PatrolBoatView` doesn't need to take the `user` or `dutyView` as parameters
[-] Use the custom data when storing the `Report` Object for `reportingOfficer`
[-] Make report be an optional parameter for `ReportNavigationRootView`
[-] Clean up indentation issues
fixes #59
> Set the reportingOfficer in Reports using the User custom data

- o-fish-ios/Views/Components/AddAttachmentsButton.swift
- o-fish-ios/Views/ReportFlow/Activity/ActivityItemView.swift
- o-fish-ios/Views/ReportFlow/Activity/ActivityView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchOnBoardView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewMemberInputView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewMemberView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselInformationInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselInformationView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationCreateCrewMemberView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationSeizureInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationsView.swift
[-] Pass the `id` of the new Report's view model down through the view hierarchy
[-] Use the Report id to set Photo.referencingReportID for all Photo Objects being added to this Report
fixes #116
> Use correct ID when setting Photo.referencingReportID

- o-fish-ios/Model/Settings.swift
- o-fish-ios/Views/LoginView.swift
- o-fish-ios/Views/MainNavigationRootView.swift
- o-fish-ios/Views/PatrolBoat/DutyState.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/LoadingVesselRecordView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
Store Realm `User` as an `EnvironmentObject` (within `Settings`)
[x] Add `realUser` to `Settings` class
[x] Add `Settings` as an environment object
[x] Use `realmUser` from the views
[x] Remove the `loggedIn` state
fixes #253 
fixes #235
> Syncuser realm access

- o-fish-ios/Views/Components/AlertItem.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] Pass the alert object down to vessel and crew view
[-] Remove use of raw `.alert/Alert` calls
[-] Add extra previews for testing alerts
fixes #307 #305
> Fix prefilling of Vessel and Crew

- o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
- o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
- o-fish-ios/Views/ReportDetails/RiskSummaryView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
[-] Fixed Don't offer to prefill crew if previous report didn't include any crew
[-] Fixed title "No photos or notes" when amber exist.
[-] Fixed Do not bring over notes for vessel information
[-] Fixed Do not bring over notes for crew information
Fixes #271, #272, #273, #277
> No photos or notes

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/Components/Picker/Country/CountryPickerDataView.swift
- o-fish-ios/Views/Components/Picker/Country/CountryPickerView.swift
- o-fish-ios/Views/ReportDetails/VesselSummaryView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseNationalityView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselInformationInputView.swift
Hey there! I am happy to contribute to your repository as part of Hacktoberfest 2020
This PR Closes #332 
Some rationale behind my changes:
• I renamed `image` variable to `code` in `CountryPickerData` because it is quite because previous name is quite ambiguous and misleading per se. So now variable `code` basically describes what kind of value it holds (short country code). `image` variable was used only once when magically retrieving country emoji, and even in that context it makes more sense to write function like `flag(for countryCode: String)`
• This change basically enabled me to retrieve `$0.code` directly and assign it to `vessel.nationality` in binding closure without introducing ambiguity (it'd be less obvious if it was `self.vessel.nationality = $0.image`, but it'd have worked …
> Store country code in Vessel Information page

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/Double+CleanValue.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
Fixes #319
Added an extension to double for presenting a clean string value in the weight input field.
> Improve number input into weight input field.

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/Components/DoneTextField.swift
- o-fish-ios/Views/Components/InputField.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
Fixes #220 
- NA I was assigned the linked issue (not required)
Added a custom text field to make use of the UITextField's inputAccessoryView property to add a toolbar with the Done button.
* **Optional: Add any relevant screenshots here** 
|    |   |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/36312970/95667374-eb051980-0b19-11eb-91d8-0f7933daf5a0.png" width="300"/> | <img src="https://user-images.githubusercontent.com/36312970/95667376-f5271800-0b19-11eb-9b07-610f9b99f34b.png" width="300"/> |
> Add done button on keyboard to fix issue #220

- o-fish-ios/Info.plist
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/ViewModel/User/UserSettings.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
Fixes #373 
* `UIUserInterfaceStyle` is set to `Automatic`
* Updating of `SceneDelegate` is removed from `UserSettings`
* `SceneDelegate` is subscribed on `UserSettings` property changes instead
* `preferredColorScheme` calls in views are removed as redundant
> Use device appearance when Force Dark Mode option is turned off

- o-fish-ios/Assets.xcassets/ComponentsColors/oSearchBar.colorset/Contents.json
- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Views/Components/Icons/IconLabel.swift
- o-fish-ios/Views/Components/Picker/SearchBarView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
Find dark mode for records search page
Fixes #
> Dark mode: Find records

- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
Delete draft reports after log out
> Delete draft reports after log out

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/Components/UnitPickerField.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
Unit picker was broken in iOS 15.
> Fix unit picker 

- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
> Save a draft report every time the user navigates to another panel #301

- o-fish-ios/Views/DraftBoardings/DraftBoardingsView.swift
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
Many screens have incorrect header colors.
How it was:
After fix:
> Incorrect header colors in dark mode

- o-fish-ios/Assets.xcassets/SingleAppearanceColors/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/actionBlue.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/appGray.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/backgroundGrey.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/blackWithOpacity.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/bubbles.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/captainGray.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/crusoe.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/darkRed.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/darkSpringGreen.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/faluRed.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/iconGreen.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/iconsGray.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/lightGrayButton.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/lightGrayIcon.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/lightSpringGreen.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/lilyWhite.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/main.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/moonLightYellow.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/moonYellow.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/oasis.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/persianLightRed.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/persianRed.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/removeAction.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/rowAmber.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/spanishOrange.colorset/Contents.json
- o-fish-ios/Assets.xcassets/SingleAppearanceColors/vanillaIce.colorset/Contents.json
- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Helpers/Color+Theme.swift
- o-fish-ios/Views/Components/RectangleButton.swift
All colors have been moved to assets. Unused colors have been removed.
> Cleanup: don't use hardcoded text and colors #374

- o-fish-ios/Views/ReportFlow/Crew/CrewMemberView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
Removed the ability to edit for crew view
> Captain and Crew remove extra click

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
Session saved and user status changed to "not at sea" after logging out.
> Log out + Not at Sea

- o-fish-ios/Model/Report/Report.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
Fixes:
- Saving a boarding record adds MPA field if appropriate
> Saving MPA data

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/Screen+Extension.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseEMSView.swift
Fixes:
- changed to an abbreviation for small screens.
> `Electronic Monitoring System` title overlaps CANCEL button 

- o-fish-ios/Views/LoginView.swift
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
had to use realmUser info instead of user variables - put in a TODO to figure out a real fix instead of this workaround.
Fixes #
> fixing blank profile user
