WildAid/o-fish-ios

- Podfile
> Update Podfile to public Realm beta

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/UIView+Constraings.swift
- o-fish-ios/ViewModel/Report/CatchViewModel.swift
- o-fish-ios/Views/Components/CallToActionButton.swift
- o-fish-ios/Views/Components/DatePickerWithButton.swift
- o-fish-ios/Views/Components/Popover/PopoverManager.swift
- o-fish-ios/Views/Components/RectangleButton.swift
- o-fish-ios/Views/Components/RemovableViewModifier.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/Catch/UnitPickerWithButton.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationSeizureInputView.swift
[-] Added PopoverManager to make fullscreen popovers from SwiftUI
[-] Added RectangleButton component
[-] Added UIView+Constraings helper for UIView logic
[-] Redesign of DatePickerWithButton.swift and
UnitPickerWithButton.swift
[-] Cleanup of unneded TODO comments
[-] Some restyle & cleanup
Fixes #4
> Align design for scrolling pickers

- o-fish-ios/Model/MenuData.swift
- o-fish-ios/Model/Photo.swift
- o-fish-ios/Model/Report/Report.swift
- o-fish-ios/Model/User/DutyChange.swift
- o-fish-ios/ViewModel/Report/PhotoViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/ViewModel/User/DutyChangeViewModel.swift
[-] Remove `agency` from models
[-] Remove `agency` from view models
fixes #61
> Remove realm partition/agency from Realm Objects

- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Views/Components/CaptionLabel.swift
- o-fish-ios/Views/Components/ColumnText.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordItemView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
> Recent Boarding and Vessel Header design improvements

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/UIImage+Thumbnail.swift
- o-fish-ios/Views/Components/LocationButton.swift
- o-fish-ios/Views/Components/Pictures/PhotoCaptureController.swift
- o-fish-ios/Views/Components/Pictures/PhotoThumbNail.swift
- o-fish-ios/Views/PatrolBoat/CoordsBoxView.swift
[-] Added extension for UIImage for creating thumbnails
[-] Implemented to create thumbnails in logic
Fixes #45, #55
> Include a thumbnail when a photo is taken

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/View+NavigationStyle.swift
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/Views/Components/NavigationBarViewModifier.swift
- o-fish-ios/Views/LoginView.swift
- o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
[-] Added View+NavigationStyle.swift to make Stack Style for
navigation
[-] Added NavigationBarViewModifier.swift with ability to change
the UIKit navigation bar appearance
[-] Added the separator for LoginView and TopTabBarContainer
[-] Improved the BoardingRecordView and Login top spacing on scroll
Fixes #44
> NavigationBar White background

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Helpers/Font+title2+titile3.swift
- o-fish-ios/Views/Components/LabeledDoubleOutput.swift
- o-fish-ios/Views/Components/TitleLabel.swift
- o-fish-ios/Views/LoginView.swift
- o-fish-ios/Views/PatrolBoat/BoardButton.swift
- o-fish-ios/Views/PatrolBoat/CoordsBoxView.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PatrolBoat/TextToggle.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/LoadedStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
- o-fish-ios/Views/ReportDetails/StatusSymbolView.swift
[-] Fixed font size on Find Records
[-] Quick fix another screens.
Fixes #50, #49, #46
> Record list item

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
[-] Added logout confirmation and localization for it
[-] Refactored the alerts on PartrolBoatView to use AlertItem
Fixes #47
> Logout confirmation alert

- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Helpers/Double+LocationDegrees.swift
- o-fish-ios/Views/Components/Icons/AddAttachmentIconView.swift
- o-fish-ios/Views/Components/Icons/EditIconView.swift
- o-fish-ios/Views/Components/Icons/ExclamationIconView.swift
- o-fish-ios/Views/Components/MinusIconView.swift
- o-fish-ios/Views/Components/Pictures/PhotoThumbNail.swift
[-] Fixed coordinates to format N53°52'25"
[-] Fixed background and size for MinusIconView
[-] Changed foreground color for addAttachmentIcon and EditIcon
Fixes #103, #92, #95, #96
> Latitude and longitude precision

- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
- o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
- o-fish-ios/Views/ReportDetails/InspectionSummaryView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/Notes/NotesView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] Added safe area ignoring for VesselRecord and BoardingRecord
and InspectionSummary
[-] Improved bottom button layout for Create Report Flow
Fixes #53
> Gray background for all the needed screens

- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Helpers/Font+title2+titile3.swift
- o-fish-ios/Views/ReportDetails/StatusSymbolView.swift
- o-fish-ios/Views/ReportFlow/Risk/TrafficLightButton.swift
[-] Refactored TrafficLightButton.swift, added opacity to colors
[-] Removed opacity from StatusSymbolView
[-] Fixed the weight of fonts for both
Fixes #75
> Risk Level color improvements

- o-fish-ios/Views/PreboardingFlow/PreboardingView/LoadedStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
[-] Reordered "Add new vessel" button from bottom to top
> Pre-boarding search results

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/Views/Components/ActionSheetButton.swift
- o-fish-ios/Views/Components/AddAttachmentsButton.swift
- o-fish-ios/Views/Components/AddAttachmentsModalView.swift
- o-fish-ios/Views/Components/LogoutModalView.swift
- o-fish-ios/Views/Components/Popover/PopoverManager.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
[-] Created LogoutModalView
[-] Implemented in PatrolBoatView LogoutModalView
Fixes #47
> Logout Modal

- o-fish-ios/Views/Components/DatePickerWithButton.swift
- o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
- o-fish-ios/Views/ReportFlow/BasicInfo/DateTimeView.swift
[-] Added functionality for editing date and time
[-] Implemented this functionality
Fixes #106, #84
> Edit date and time

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/PatrolBoat/DutyReportsView.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
[-] Reused design from Vessel Reports 
Fixes #24
> Added DutyReportsView when going off duty

- o-fish-ios/Views/Components/CallToActionButton.swift
[-] Changed font for arrow
Fixes #85
> Next button

- o-fish-ios/Views/Components/LabeledText.swift
- o-fish-ios/Views/PatrolBoat/DutyReportsView.swift
- o-fish-ios/Views/ReportDetails/CatchItemView.swift
- o-fish-ios/Views/ReportDetails/CrewItemView.swift
- o-fish-ios/Views/ReportDetails/EMSSummaryView.swift
- o-fish-ios/Views/ReportDetails/LastDeliverySummaryView.swift
- o-fish-ios/Views/ReportDetails/VesselSummaryView.swift
- o-fish-ios/Views/ReportDetails/ViolationStaticItemView.swift
[-] Added preview for DutyReportsView
[-] Aligned fields in container using alignment: .top
fixes #79
> Container template changes

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/ImageLoading/AsyncImage.swift
- o-fish-ios/Views/Components/Icons/VesselIconView.swift
- o-fish-ios/Views/Components/PageView/PageControl.swift
- o-fish-ios/Views/Components/PageView/PageView.swift
- o-fish-ios/Views/Components/PageView/PageViewController.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingLoadedStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/PhotoQueryManager.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
[-] Added carousel view aka PageView and needed bridge components
[-] Added PhotoQueryManager to reuse Realm fetch code for Images
[-] Integrated photos for Detail and List views
[-] Renamed LoadedStateView to PreboardingLoadedStateView
Fixes #18
> Vessel photo on search and boarding details

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/Components/BoardVesselButton.swift
- o-fish-ios/Views/Components/SectionButton.swift
- o-fish-ios/Views/PatrolBoat/DutyReportsView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
- o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
- o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
[-] Padding and font on remove button
[-] changed map height according design
[-] Created "Board vessel" button on BoardingView
Fixes #83, #98, #113
> Board vessel button

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/AppDelegate.swift
- o-fish-ios/Helpers/Constants.swift
- o-fish-ios/Helpers/NotificationManager.swift
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/ViewModel/User/SampleUserViewModel.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingLoadedStateView.swift
[-] Implemented notification after 4 hours after closing app
[-] Implemented notification after 10 hours after starting duty.
Fixes #25, #26
> Prompt are you still on duty

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/Views/Components/PageView/PageViewController.swift
- o-fish-ios/Views/Components/StartStopDatePicker.swift
- o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
> Fix build warnings

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Info.plist
[-] Change the bundle id to `org.wildaid.o-fish`
[-] Mark the app as not containing encryption software
[-] Increment the build number
Fixes #124
> Change the bundle id

- privacy-sample.md
> Add sample privacy policy

- o-fish-ios/Helpers/Constants.swift
- o-fish-ios/Views/Components/Pictures/PhotoCaptureController.swift
[-] JPEG compression to 3 MB setup
Fixes #27
> Added Image Compressing to configured size

- o-fish-ios/Helpers/NotificationManager.swift
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
[-] Added logic for notification after logout
[-] Added logic  for reset timer after app is brought into the foreground
fixes #135, #139
> Getting 4-hour on-duty notifications even when off-duty

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/ViewModel/Report/OffenceViewModel.swift
- o-fish-ios/ViewModel/Report/ViolationViewModel.swift
- o-fish-ios/Views/Components/Picker/Violation/ViolationPickerDataView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
[-] Changed separator from "\n" to " "
[-] Fixed bug with localization
Fixes #131, #133
> Violation title shouldn't be broken into 2 rows

- o-fish-ios/Views/Components/Pictures/PhotoCaptureController.swift
> Allow photo library to be used for attachments

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/RealmConnection.swift
- o-fish-ios/Views/Components/Icons/PersonIconView.swift
- o-fish-ios/Views/Components/PhotoView.swift
- o-fish-ios/Views/PatrolBoat/DutyState.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PatrolBoat/VesselImageView.swift
[-] Distinguish PatrolBoatUserView.swift
[-] Added parsing and integration of profile picture from custom
data from Realm
[-] Created PhotoView for PhotoViewModel handling and integrated
[-] Improved issue with DutyState and moved to separate file
Fixes #138
> Integrate a profile picture

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/ImageLoading/VesselAsyncImage.swift
- o-fish-ios/Views/Components/PageView/PageViewController.swift
- o-fish-ios/Views/Components/Pictures/PhotoVesselView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
[-] Increased size for thumbnails for VesselAttachments from 102 to 375
[-] Fixed crash with UIPageViewController for 2 items.
Fixes #134
> Banner image pixelated

- o-fish-ios/Helpers/LocationHelper.swift
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
> Improved LocationHelper

- o-fish-ios/Model/Settings.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/SnapshotManager/LocationSnapshotManager.swift
> Changed all maps default zoom level to 200 mi

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/KeychainWrapper.swift
- o-fish-ios/Info.plist
- o-fish-ios/Model/Settings.swift
- o-fish-ios/Views/LoginView.swift
[-] Implemented Keychain wrapper for storing login and password.
> FaceID Auth

- o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
[-] "Crew member" title
[-] Fixed count of crew members.
Fixes #164
> Incorrect crew member count

- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
> Do not show blank business

- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
[-] Changed logic for adding vessel for previous boardings.
Fixes #163
> Previous 5 boardings not sorted properly

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/Components/BoardVesselButton.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationCreateCrewMemberView.swift
> Localization improvements

- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
Fixes typo/bug with default action (logout should be default, change picture should be optional)
> Correct logout option

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
[-] Fixed title with 0 crew
[-] Remove unneeded localization key "Shadow..."
[-] Captain is part of crew now.
Fixes #185, #182
> 0 Crew should be "Members"

- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
[-] Added cancel alert before discard report.
Fixes #183
> Cancel boarding

- O-FISHTests/CatchViewModelTests.swift
- O-FISHTests/CrewMemberViewModelTests.swift
- O-FISHTests/EMSViewModelTests.swift
- o-fish-ios/ViewModel/Report/CatchViewModel.swift
- o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
- o-fish-ios/ViewModel/Report/EMSViewModel.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchOnBoardView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewMemberInputView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] VesselView - EMSInputView
[-] CrewView
[-] CatchView
[-] Handled validation case with removing crew member
from violation screen
Partly fixes #172
> Added first items and validation of items for

- o-fish-ios/ViewModel/Report/CatchViewModel.swift
Added ability to see pounds for USA users in the first. 
Fixes #192
> Catch Weight #29

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/Components/AlertItem.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
[-] Added alert after submitting boarding.
Fixes #191
> Boarding submitted modal when submitting a boarding

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
> Changing Cancel modal worlds

- .github/workflows/main.yml
This will fix the build check for main branch
> Change main branch name on CI/CD

- o-fish-ios/Views/Components/BoardVesselButton.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
Now it starts boarding immediately if alert button "Yes" was pressed
Fixes #201
> Going on Duty when Board Vessel is selected

- Podfile
- Podfile.lock
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/RealmConnection.swift
- o-fish-ios/Views/Components/BoardVesselButton.swift
- o-fish-ios/Views/Components/ModalView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/BusinessPickerData.swift
[-] Update Podfile to refer to use `10.0.3` version of the Realm SDK
[-] Fix code to work with the new API
[-] Minor lint fixes
[-] Cleanup build/lint warnings
[-] Fixes #63
> Port to Realm Sync Beta 3

- o-fish-ios/Views/Components/BoardVesselButton.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] Added ability to add attachments to prefill vessel
Fixes #226
> Prefill attachments for vessel

- O-FISHTests/OffenceViewModelTests.swift
- O-FISHTests/SafetyLevelViewModelTests.swift
- O-FISHTests/ViolationViewModelTests.swift
- o-fish-ios/ViewModel/Report/OffenceViewModel.swift
- o-fish-ios/ViewModel/Report/ViolationViewModel.swift
- o-fish-ios/Views/Components/Picker/Violation/ViolationPickerDataView.swift
- o-fish-ios/Views/Components/Picker/Violation/ViolationPickerView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseViolationsView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
- Now there is no "California" in every violation
> "California" is keep getting added fix

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios.xcodeproj/xcshareddata/xcschemes/o-fish-ios.xcscheme
- o-fish-ios/ViewModel/Report/SampleReportViewModel.swift
- o-fish-ios/Views/ReportDetails/BoardingRecordView.swift
- o-fish-ios/Views/ReportDetails/RiskSummaryView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] Added Risk view to the Boarding report
[-] Fixed Realm crash when saving report with prefilled vessel information
[-] Fixed button title on Cancel boarding alert
Fixes #202, #223, #232, #251
> Risks on Boarding Reports

- o-fish-ios/Views/Components/ButtonField.swift
- o-fish-ios/Views/Components/CaptionLabel.swift
- o-fish-ios/Views/Components/ColumnText.swift
- o-fish-ios/Views/Components/Icons/IconLabel.swift
- o-fish-ios/Views/Components/InputField.swift
- o-fish-ios/Views/Components/LabeledDoubleOutput.swift
- o-fish-ios/Views/Components/LabeledText.swift
- o-fish-ios/Views/Components/LabeledTextInput.swift
- o-fish-ios/Views/Components/MultilineTextView.swift
- o-fish-ios/Views/Components/Picker/Business/BusinessPickerDataView.swift
- o-fish-ios/Views/Components/Picker/Country/CountryPickerDataView.swift
- o-fish-ios/Views/Components/Picker/SearchBarView.swift
- o-fish-ios/Views/Components/Picker/TextPickerView.swift
- o-fish-ios/Views/Components/Picker/Violation/ViolationPickerDataView.swift
- o-fish-ios/Views/LoginView.swift
- o-fish-ios/Views/PatrolBoat/ColoredToggleStyle.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
- o-fish-ios/Views/PatrolBoat/SearchBarButton.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/EmptyStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/VesselItemView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordHeaderView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordItemView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
- o-fish-ios/Views/ReportDetails/DateTimeStackView.swift
- o-fish-ios/Views/ReportDetails/StatusSymbolView.swift
- o-fish-ios/Views/ReportFlow/CrewMemberShortView.swift
[-] Fixed all fonts
Fixes #108
> Add accessible fonts it is on design

- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
[-] Added emptyReport to avoid bug
Fixes #175
> Location reset when moving back to basic info view

- o-fish-ios/Views/Components/Picker/SearchableView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseCrewMemberView.swift
[-] Added cancel button and title to all pickers
Fixes #90
> Add cancel button to pickers view

- o-fish-ios/Views/LoginView.swift
> On login view, show progress view until everything has completed

- o-fish-ios/Model/Settings.swift
> `menuData` shouldn't be `@Published` or it creates a loop

- Localization/es-419.lproj/Localizable.strings
> fixing "Find Records"

- o-fish-ios/Model/Report/Boat.swift
- o-fish-ios/Model/Settings.swift
- o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
- o-fish-ios/ViewModel/Report/DeliveryViewModel.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/ReportDetails/LastDeliverySummaryView.swift
- o-fish-ios/Views/ReportFlow/ChooseScreens/ChooseBusiness/ChooseBusinessView.swift
> Make lastDelivery optional in model

- o-fish-ios/Model/Report/Report.swift
- o-fish-ios/ViewModel/Report/DeliveryViewModel.swift
- o-fish-ios/ViewModel/Report/PhotoViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
[-] Add `draft` to model as an optional
[-] Add `draft` to view model
[-] Remove some debug `print` commands
fixes #242
> Add `draft` optional Bool to Reports

- o-fish-ios/Views/LoginView.swift
> Clear loading screen if login fails

- o-fish-ios/Model/Report/Report.swift
- o-fish-ios/ViewModel/Report/AnnotatedNoteViewModel.swift
- o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
- o-fish-ios/ViewModel/Report/BoatViewModel.swift
- o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
- o-fish-ios/ViewModel/Report/InspectionViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/ViewModel/Report/SummaryViewModel.swift
- o-fish-ios/ViewModel/User/NameViewModel.swift
- o-fish-ios/ViewModel/User/UserViewModel.swift
> Make model and view-model mutable

- O-FISHTests/BoatViewModelTests.swift
- O-FISHTests/CatchViewModelTests.swift
- O-FISHTests/ReportViewModelTest.swift
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/ViewModel/Report/PhotoViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
[-] Add cascading deletes for the Report Object and view model
[-] Fix unit tests broken by previous changes to the model/view model
[-] Add unit test case for `ReportViewModel` - saving and deleting a report
fixes #300
> Add cascading deletes to model/view model for Reports

- o-fish-ios/Views/Components/Picker/SearchableView.swift
> Other always appears in searchable view

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Design/Color+Design.swift
- o-fish-ios/SceneDelegate.swift
- o-fish-ios/Views/Components/ActionSheetItem.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
[-] Added ActionSheetItem.
[-] Implemented Cancel Boarding Model
[-] Implemented Save Boarding Modal
Fixes #291, #292, #293, #297
> Cancel Boarding Modal change

- o-fish-ios/ViewModel/User/DutyChangeViewModel.swift
- o-fish-ios/ViewModel/User/NameViewModel.swift
- o-fish-ios/ViewModel/User/UserViewModel.swift
- o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
> Avoid reusing embedded Objects in multiple Objects

- o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
- o-fish-ios/ViewModel/Report/BoatViewModel.swift
- o-fish-ios/ViewModel/Report/CatchViewModel.swift
- o-fish-ios/ViewModel/Report/CrewMemberViewModel.swift
- o-fish-ios/ViewModel/Report/EMSViewModel.swift
- o-fish-ios/ViewModel/Report/InspectionViewModel.swift
- o-fish-ios/ViewModel/Report/OffenceViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/ViewModel/Report/SummaryViewModel.swift
- o-fish-ios/ViewModel/Report/ViolationViewModel.swift
> Ensure VMs don't hold onto deleted model Objects

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/DraftBoardings/DraftBoardingLoadedStateView.swift
- o-fish-ios/Views/DraftBoardings/DraftBoardingsView.swift
- o-fish-ios/Views/DraftBoardings/EmptyDraftView.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/LoadingVesselRecordView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselView.swift
[-] Added functionality for button Draft Boardings on Home Page
[-] Added DraftBoardingsView with components (3 State)
[-] Added functionality for edit draft boardings and return on DraftBoardingsView
Fixes #294, #295, #296, #298
> Draft boardings on home page

- Localization/es-419.lproj/Localizable.strings
- Localization/fr.lproj/Localizable.strings
- Localization/uk.lproj/Localizable.strings
- o-fish-ios/Views/Components/CallToActionButton.swift
- o-fish-ios/Views/Components/SegmentedField.swift
- o-fish-ios/Views/PatrolBoat/PatrolBoatUserView.swift
- o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift
- o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
- o-fish-ios/Views/ReportFlow/CrewMemberShortView.swift
- o-fish-ios/Views/ReportFlow/Risk/TrafficLightButton.swift
[-] Implemented not at sea with drafts
[-] Fixed rounded size.
Fixes #299, #320
> Not at sea and drafts

- o-fish-ios/Views/Components/Maps/MapDisplayView.swift
- o-fish-ios/Views/ReportDetails/Map/LocationDisplayView.swift
[-] Added center in the mapViewDidChangeVisibleRegion(_ mapView: MKMapView)
Fixes #257
> Position moves when zooming

- .gitignore
- README.md
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Helpers/Constants.swift
- o-fish-ios/Helpers/KeychainWrapper.swift
- o-fish-ios/LocalConstants.swift
- o-fish-ios/Model/Settings.swift
> Move `realmAppId` to a git-ignorable file

- o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
Hey there! I am happy to contribute to your repository as part of Hacktoberfest 2020
This PR Closes #246
> Change EMS registry number input field keyboard type to numeric

- pull_request_template.md
Digital Ocean recommends a PR template for hacktobervest and this was approved by CZ and RQ.
> adding PR template

- o-fish-ios/Views/ReportFlow/Vessel/VesselInformationInputView.swift
> Make permit number appear in all caps on vessel information page

- README.md
> Readme app

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/ViewModel/Report/AttachmentsViewModel.swift
- o-fish-ios/ViewModel/Report/NoteViewModel.swift
- o-fish-ios/ViewModel/Report/SampleReportViewModel.swift
- o-fish-ios/Views/Components/AddAttachmentsButton.swift
- o-fish-ios/Views/Components/InputField.swift
- o-fish-ios/Views/Components/NoteFieldView.swift
- o-fish-ios/Views/Components/NotesListView.swift
- o-fish-ios/Views/ReportDetails/ActivitySummaryView.swift
- o-fish-ios/Views/ReportDetails/CatchItemView.swift
- o-fish-ios/Views/ReportDetails/CrewItemView.swift
- o-fish-ios/Views/ReportDetails/EMSSummaryView.swift
- o-fish-ios/Views/ReportDetails/InspectionSummaryView.swift
- o-fish-ios/Views/ReportDetails/LastDeliverySummaryView.swift
- o-fish-ios/Views/ReportDetails/RiskSummaryView.swift
- o-fish-ios/Views/ReportDetails/VesselSummaryView.swift
- o-fish-ios/Views/ReportDetails/ViolationStaticItemView.swift
- o-fish-ios/Views/ReportFlow/Activity/ActivityItemView.swift
- o-fish-ios/Views/ReportFlow/AttachmentsView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchInputView.swift
- o-fish-ios/Views/ReportFlow/Catch/CatchStaticView.swift
- o-fish-ios/Views/ReportFlow/Crew/CrewMemberInputView.swift
- o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
- o-fish-ios/Views/ReportFlow/Vessel/VesselInformationInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationCreateCrewMemberView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationInputView.swift
- o-fish-ios/Views/ReportFlow/Violations/ViolationSeizureInputView.swift
> Show new (empty) notes immediately, fix note deletion iOS issue

- o-fish-ios/Views/ReportDetails/StatusSymbolView.swift
- o-fish-ios/Views/ReportFlow/Risk/TrafficLightButton.swift
- o-fish-ios/Views/ReportFlow/Risk/TrafficLights.swift
Fixes #287 
I know, #287 is already assigned to somebody, but there are no updates for several weeks, so I'd like to suggest my fix
> Fixes for Risk rendering

- Scripts/README-update_loc.md
- Scripts/update_loc.swift
> 383 Add SkipList to Localization Scripts

- O-FISHTests/AttachmentsViewModelTests.swift
- O-FISHTests/BoatViewModelTests.swift
- O-FISHTests/CatchViewModelTests.swift
- O-FISHTests/DeliveryViewModelTests.swift
- O-FISHTests/InspectionViewModelTests.swift
- O-FISHTests/MockDataProvider.swift
- O-FISHTests/ReportViewModelTest.swift
- O-FISHTests/SummaryViewModelTests.swift
- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/ViewModel/DataProvider.swift
- o-fish-ios/ViewModel/Report/BoatViewModel.swift
- o-fish-ios/ViewModel/Report/InspectionViewModel.swift
- o-fish-ios/ViewModel/Report/PhotoViewModel.swift
- o-fish-ios/ViewModel/Report/ReportViewModel.swift
- o-fish-ios/ViewModel/Report/SummaryViewModel.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
> Tests target compilation is fixed and all tests are passing

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
> removing button from avatar

- o-fish-ios/Model/Settings.swift
- o-fish-ios/Views/Components/AlertItem.swift
- o-fish-ios/Views/PreboardingFlow/VesselRecordView/VesselRecordView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
The maximum number of drafts is limited to ten
> Add draft limitation

- o-fish-ios/Views/Components/Picker/DatePickerController.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
> Set last delivery date to today

- o-fish-ios/Views/Components/InputField.swift
- o-fish-ios/Views/Components/TextField/FocusableTextFieldAdapter.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/ReportFlow/Vessel/DeliveryInputView.swift
https://user-images.githubusercontent.com/52383559/165082807-e3592b26-eedb-489a-aca8-9735d5e8ab21.mp4
> Indication to add a new business

- o-fish-ios.xcodeproj/project.pbxproj
- o-fish-ios/Views/Components/Maps/MapComponentView.swift
- o-fish-ios/Views/Components/Maps/MapView.swift
- o-fish-ios/Views/Components/Maps/TextFieldAlertModifier.swift
- o-fish-ios/Views/DraftBoardings/DraftBoardingLoadedStateView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
- o-fish-ios/Views/ReportFlow/BasicInfo/BasicInfoView.swift
- o-fish-ios/Views/ReportFlow/ReportNavigationRootView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
https://user-images.githubusercontent.com/52383559/163564377-6e097fa5-e17d-4d6b-a34b-b1b344ff9bd8.mp4
> Added ability to change location

- o-fish-ios/Views/PatrolBoat/ProfilePageView.swift
- o-fish-ios/Views/PreboardingFlow/PreboardingView/PreboardingView.swift
https://user-images.githubusercontent.com/52383559/163564615-843fc003-79d0-41df-882e-f3ee08bf6404.mp4
> Update profile photo

- o-fish-ios/Views/Components/ScrollableTabBar/ScrollableTabBar.swift
- o-fish-ios/Views/Components/ScrollableTabBar/ScrollableTabBarItemView.swift
- o-fish-ios/Views/ReportFlow/TopTabBarContainerView.swift
Fixes #
- 
[Video](https://user-images.githubusercontent.com/52383559/176178150-a564af19-0bd3-4b9d-af5f-cc6ff1567c5c.mp4)
> Tab navigation

- o-fish-ios/Views/Components/Maps/MapView.swift
> fixes issue 462
